server:
  port: 8087
spring:
  application:
    name: recommendation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_recommendation
    username: ecom_user
    password: ecom_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: recommendation-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.gocommerce.recommendation.events.OrderCreatedEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      service: recommendation-service
    distribution:
      percentiles-histogram:
        http.server.requests: true
