server:
  port: 8083

spring:
  application:
    name: cart-service

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: cart-service

security:
  jwt:
    secret: "this_is_a_dev_secret_change_later_1234567890"
