server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: cart-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:0}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      service: cart-service
    distribution:
      percentiles-histogram:
        http.server.requests: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
