server:
  port: 8084

spring:
  application:
    name: search-service

  elasticsearch:
    uris: http://localhost:9200

  data:
    redis:
      host: localhost
      port: 6379
      database: 2

catalog:
  base-url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics  # expose metrics too
  endpoint:
    health:
      show-details: always                       # show CB details in /actuator/health
  health:
    circuitbreakers:
      enabled: true                              # enable resilience4j health contributors
  metrics:
    tags:
      service: search-service
    distribution:
      percentiles-histogram:
        http.server.requests: true

resilience4j:
  circuitbreaker:
    instances:
      catalogClient:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

      searchCore:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 50
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true

      reindexJob:                                # used by @CircuitBreaker on reindexProducts()
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
