apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gocommerce-staging

resources:
  - ../../../k8s/migrations

images:
  - name: auth-service
    newName: ghcr.io/OWNER/REPOSITORY/auth-service
    newTag: sha-REPLACE_ME
  - name: catalog-service
    newName: ghcr.io/OWNER/REPOSITORY/catalog-service
    newTag: sha-REPLACE_ME
  - name: order-service
    newName: ghcr.io/OWNER/REPOSITORY/order-service
    newTag: sha-REPLACE_ME
  - name: analytics-service
    newName: ghcr.io/OWNER/REPOSITORY/analytics-service
    newTag: sha-REPLACE_ME
  - name: recommendation-service
    newName: ghcr.io/OWNER/REPOSITORY/recommendation-service
    newTag: sha-REPLACE_ME
