# src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_catalog
    username: ecom_user
    password: ecom_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # dev only
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: catalog-service
