server:
  port: 8082

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_catalog
    username: ecom_user
    password: ecom_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # dev only
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics   # expose metrics too
  endpoint:
    health:
      show-details: always                        # so CB states are visible
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      service: catalog-service
    distribution:
      percentiles-histogram:
        http.server.requests: true

security:
  jwt:
    secret: "this_is_a_dev_secret_change_later_1234567890"

resilience4j:
  circuitbreaker:
    instances:
      searchIndex:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20           # last 20 calls
        failure-rate-threshold: 50        # % failures to open
        wait-duration-in-open-state: 10s  # stay open 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
